#!/bin/bash

git clone https://github.com/projectdiscovery/nuclei-templates
git clone https://github.com/0x727/ObserverWard_0x727
git clone https://github.com/0xAwali/Virtual-Host
git clone https://github.com/0xPugazh/my-nuclei-templates
git clone https://github.com/0xmaximus/final_freaking_nuclei_templates
git clone https://github.com/1in9e/my-nuclei-templates
git clone https://github.com/5cr1pt/templates
git clone https://github.com/ARPSyndicate/kenzer-templates
git clone https://github.com/Akokonunes/Private-Nuclei-Templates
git clone https://github.com/Arvinthksrct/alltemplate
git clone https://github.com/AshiqurEmon/nuclei_templates.git
git clone https://github.com/CharanRayudu/Custom-Nuclei-Templates
git clone https://github.com/DoubleTakes/nuclei-templates
git clone https://github.com/Elsfa7-110/mynuclei-templates
git clone https://github.com/ExpLangcn/NucleiTP
git clone https://github.com/Harish4948/Nuclei-Templates
git clone https://github.com/Hunt2behunter/nuclei-templates
git clone https://github.com/Jagomeiister/nuclei-templates
git clone https://github.com/JoshMorrison99/url-based-nuclei-templates
git clone https://github.com/Kaue-Navarro/Templates-kaue-nuclei
git clone https://github.com/KeepHowling/all_freaking_nuclei_templates
git clone https://github.com/Lopseg/nuclei-c-templates
git clone https://github.com/MR-pentestGuy/nuclei-templates
git clone https://github.com/NightRang3r/misc_nuclei_templates
git clone https://github.com/NitinYadav00/My-Nuclei-Templates
git clone https://github.com/Odayex/Random-Nuclei-Templates
git clone https://github.com/PedroFerreira97/nuclei_templates
git clone https://github.com/R-s0n/Custom_Vuln_Scan_Templates
git clone https://github.com/Saimonkabir/Nuclei-Templates
git clone https://github.com/Saptak9983/Nuclei-Template
git clone https://github.com/ShangRui-hash/my-nuclei-templates
git clone https://github.com/freakyclown/Nuclei_templates
git clone https://github.com/SirAppSec/nuclei-template-generator-log4j
git clone https://github.com/Str1am/my-nuclei-templates
git clone https://github.com/SumedhDawadi/Custom-Nuclei-Template
git clone https://github.com/System00-Security/backflow
git clone https://github.com/adampielak/nuclei-templates
git clone https://github.com/aels/CVE-2022-37042
git clone https://github.com/alexrydzak/rydzak-nuclei-templates
git clone https://github.com/ayadim/Nuclei-bug-hunter
git clone https://github.com/badboy-sft/badboy_17-Nuclei-Templates-Collection
git clone https://github.com/binod235/nuclei-templates-and-reports
git clone https://github.com/blazeinfosec/nuclei-templates
git clone https://github.com/brinhosa/brinhosa-nuclei-templates
git clone https://github.com/c-sh0/nuclei_templates
git clone https://github.com/cipher387/juicyinfo-nuclei-templates
git clone https://github.com/clarkvoss/Nuclei-Templates
git clone https://github.com/coldrainh/nuclei-ByMyself
git clone https://github.com/d3sca/Nuclei_Templates
git clone https://github.com/daffainfo/my-nuclei-templates
git clone https://github.com/damon-sec/Nuclei-templates-Collection
git clone https://github.com/dk4trin/templates-nuclei
git clone https://github.com/drfabiocastro/certwatcher-templates
git clone https://github.com/ekinsb/Nuclei-Templates
git clone https://github.com/erickfernandox/nuclei-templates
git clone https://github.com/esetal/nuclei-bb-templates
git clone https://github.com/ethicalhackingplayground/erebus-templates
git clone https://github.com/geeknik/nuclei-templates-1
git clone https://github.com/geeknik/the-nuclei-templates
git clone https://github.com/glyptho/templatesallnuclei
git clone https://github.com/im403/nuclei-temp
git clone https://github.com/javaongsan/nuclei-templates
git clone https://github.com/justmumu/SpringShell
git clone https://github.com/kabilan1290/templates
git clone https://github.com/kh4sh3i/CVE-2022-23131
git clone https://github.com/luck-ying/Library-YAML-POC
git clone https://github.com/mastersir-lab/nuclei-yaml-poc
git clone https://github.com/mbskter/Masscan2Httpx2Nuclei-Xray
git clone https://github.com/medbsq/ncl
git clone https://github.com/meme-lord/Custom-Nuclei-Templates
git clone https://github.com/n1f2c3/mytemplates
git clone https://github.com/notnotnotveg/nuclei-custom-templates
git clone https://github.com/obreinx/nuceli-templates
git clone https://github.com/optiv/mobile-nuclei-templates
git clone https://github.com/p0ch4t/nuclei-special-templates
git clone https://github.com/panch0r3d/nuclei-templates
git clone https://github.com/peanuth8r/Nuclei_Templates
git clone https://github.com/pentest-dev/Profesional-Nuclei-Templates
git clone https://github.com/pikpikcu/nuclei-templates
git clone https://github.com/ping-0day/templates
git clone https://github.com/praetorian-inc/chariot-launch-nuclei-templates
git clone https://github.com/ptyspawnbinbash/template-enhancer
git clone https://github.com/rafaelcaria/Nuclei-Templates
git clone https://github.com/rafaelwdornelas/my-nuclei-templates
git clone https://github.com/rahulkadavil/nuclei-templates
git clone https://github.com/randomstr1ng/nuclei-sap-templates
git clone https://github.com/redteambrasil/nuclei-templates
git clone https://github.com/ree4pwn/my-nuclei-templates
git clone https://github.com/ricardomaia/nuclei-template-generator-for-wordpress-plugins
git clone https://github.com/sadnansakin/my-nuclei-templates
git clone https://github.com/securitytest3r/nuclei_templates_work
git clone https://github.com/sharathkramadas/k8s-nuclei-templates
git clone https://github.com/shifa123/detections
git clone https://github.com/sl4x0/NC-Templates
git clone https://github.com/smaranchand/nuclei-templates
git clone https://github.com/soapffz/myown-nuclei-poc
git clone https://github.com/soumya123raj/Nuclei
git clone https://github.com/souzomain/mytemplates
git clone https://github.com/tamimhasan404/Open-Source-Nuclei-Templates-Downloader
git clone https://github.com/test502git/log4j-fuzz-head-poc
git clone https://github.com/th3r4id/nuclei-templates
git clone https://github.com/thebrnwal/Content-Injection-Nuclei-Script
git clone https://github.com/thecyberneh/nuclei-templatess
git clone https://github.com/thelabda/nuclei-templates
git clone https://github.com/themoonbaba/private_templates
git clone https://github.com/rix4uni/BugBountyTips
git clone https://github.com/Lu3ky13/Authorization-Nuclei-Templates
git clone https://github.com/bug-vs-me/nuclei
git clone https://github.com/topscoder/nuclei-wordfence-cve
git clone https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
git clone https://github.com/toramanemre/log4j-rce-detect-waf-bypass
git clone https://github.com/trickest/log4j
git clone https://github.com/wasp76b/nuclei-templates
git clone https://github.com/wr00t/templates
git clone https://github.com/xinZa1/template
git clone https://github.com/yarovit-developer/nuclei-templates
git clone https://github.com/yavolo/nuclei-templates
git clone https://github.com/z3bd/nuclei-templates
git clone https://github.com/zer0yu/Open-PoC
git clone https://github.com/zinminphyo0/KozinTemplates
git clone https://github.com/bhataasim1/PersonalTemplates.git
git clone https://github.com/pikpikcu/my-nuclei-templates
git clone https://github.com/SirBugs/Priv8-Nuclei-Templates
git clone https://github.com/foulenzer/foulenzer-templates
git clone https://github.com/joanbono/nuclei-templates
git clone https://github.com/Nithissh0708/Custom-Nuclei-Templates
git clone https://github.com/ChiaraNRTT96/BountySkill
git clone https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31
git clone https://gist.github.com/0x240x23elu
git clone https://github.com/themastersunil/Nuclei-TamplatesBackup.git
git clone https://github.com/themastersunil/nucleiDB
git clone https://github.com/Linuxinet/nuclei-templates
git clone https://github.com/Aituglo/nuclei-templates
git clone https://github.com/0XParthJ/Nuclei-Templates
git clone https://github.com/trungkay2/Nuclei-template
git clone https://github.com/abbycantcode/Nuclei-Template
git clone https://github.com/pacho15/mynuclei_templates
git clone https://github.com/1dayluo/My-Nuclei-Templates
git clone https://github.com/themoonbaba/private_templates/blob/main/springboot_heapdump.yaml
git clone https://github.com/srkgupta/cent-nuclei-templates
git clone https://github.com/UltimateSec/ultimaste-nuclei-templates
git clone https://github.com/davidfortytwo/GetNucleiTemplates
git clone https://github.com/v3l4r10/Nuclei-Templates
git clone https://github.com/lkuik/nuclei-templates
git clone https://github.com/wearetyomsmnv/llm_integrated_nuclei_templates
git clone https://github.com/U53RW4R3/nuclei-fuzzer-templates
git clone https://github.com/edoardottt/missing-cve-nuclei-templates
git clone https://github.com/szybnev/nuclei-custom
git clone  https://github.com/r3dcl1ff/Symfony-Fuck